# Generated by Django 2.0.5 on 2020-12-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrcodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelname', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('qrimg', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
