# Generated by Django 2.0.5 on 2020-06-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200612_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='member',
            new_name='urjamember',
        ),
    ]
