# Generated by Django 2.0.5 on 2020-06-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='urjamember',
        ),
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
    ]
