# Generated by Django 2.0.5 on 2020-06-12 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='paymentmonth',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 10, 13, 54, 510136)),
        ),
    ]
