# Generated by Django 2.0.5 on 2020-06-12 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_paymentdetail_paymentmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='paymentmonth',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='paymonth',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 10, 15, 49, 915728, tzinfo=utc)),
        ),
    ]
